// Smart Import AI workflow scaffold for Lingo Bloom.
// Current public frontend performs a safe local pre-scan and creates a structured draft.
// A private backend can later replace runAIScan() with real OCR/LLM extraction without changing the UI/data model.
(function(){
  const AI_KEY='lingo-bloom-ai-content-v1';
  const AI=JSON.parse(localStorage.getItem(AI_KEY)||'null')||{courses:{}};
  const saveAI=()=>localStorage.setItem(AI_KEY,JSON.stringify(AI));
  window.AI_CONTENT=AI;

  const typeLabel={theory:'📕 Lý thuyết',mcq:'🔘 ABCD',truefalse:'☑️ Đúng / Sai',fill:'✍️ Điền',open:'📝 Tự luận',listening:'🎧 Nghe',corrige:'✅ Corrigé',transcript:'💬 Transcript'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function trackNo(name){let m=(name||'').match(/(?:piste|track|audio|mp3)[_\-\s]*(\d{1,3})/i)|| (name||'').match(/[_\-](\d{1,3})(?:\.[^.]+)?$/);return m?+m[1]:null}
  function guessDocKind(name){let x=(name||'').toLowerCase();if(/corrig|answer|réponse|reponse/.test(x))return'corrige';if(/transcript|transcription/.test(x))return'transcript';if(/exercice|exercise|test|quiz|qcm|mcq/.test(x))return'mcq';if(/gramma|theorie|theory|cours|lesson|chapitre|chapter/.test(x))return'theory';return'theory'}
  function listeningLessons(bookId){const b=BOOKS[bookId];let out=[];b.units.forEach((u,ui)=>u[1].forEach((name,li)=>{if((u[2]||[]).includes('CO')||/oral|écoute|audio|listening/i.test(name))out.push({ui,li,name,ord:ordinalFor(bookId,ui,li)})}));return out}
  function targetSelect(bookId,current,attr){let h=`<option value="book" ${current==='book'?'selected':''}>À vérifier / chưa map</option>`;BOOKS[bookId].units.forEach((u,ui)=>u[1].forEach((name,li)=>{let v=`${ui}:${li}`;h+=`<option value="${v}" ${v===current?'selected':''}>Bài ${n2(ordinalFor(bookId,ui,li))} · ${esc(name)}</option>`}));return `<select ${attr||''}>${h}</select>`}
  function proposeAudio(bookId,audios){const listening=listeningLessons(bookId);return audios.map((f,i)=>{let n=trackNo(f.name),idx=n!=null?Math.max(0,n-1):i,target=listening[idx]?`${listening[idx].ui}:${listening[idx].li}`:'book',confidence=listening[idx]?(n!=null?0.68:0.42):0.15;return{name:f.name,size:f.size,type:'Audio',track:n,target,confidence,reason:n!=null?'Tên file có số piste/track; cần đối chiếu nội dung nguồn.':'Xếp theo thứ tự file; cần kiểm tra.'}})}
  async function readSmallText(file){if(!/\.(txt|md|csv)$/i.test(file.name)||file.size>800000)return'';try{return await file.text()}catch{return''}}
  function detectBlocksFromText(text,fileName){if(!text)return[{kind:guessDocKind(fileName),title:fileName,content:'',confidence:0.25,source:fileName,status:'À vérifier'}];
    const chunks=text.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean).slice(0,120);
    return chunks.map((c,i)=>{let kind='theory';if(/\b[a-d][\).]\s.+(?:\n|\s)+[a-d][\).]/i.test(c)||/(?:a|A)[\).].*(?:b|B)[\).].*(?:c|C)[\).]/s.test(c))kind='mcq';else if(/vrai|faux|true|false/i.test(c))kind='truefalse';else if(/complétez|complete|fill|_____/.test(c))kind='fill';else if(/corrig|solution|réponse/i.test(c))kind='corrige';else if(/transcript|transcription/i.test(c))kind='transcript';else if(/écoutez|audio|piste|listening/i.test(c))kind='listening';return{kind,title:`${fileName} · bloc ${i+1}`,content:c,confidence:0.65,source:fileName,status:'Local pre-scan'}})}
  async function runAIScan(bookId,files){let docs=[],audios=[];for(const f of files){if(/\.(mp3|m4a|wav|ogg)$/i.test(f.name)){audios.push(f);continue}let text=await readSmallText(f);docs.push(...detectBlocksFromText(text,f.name))}
    let audioMap=proposeAudio(bookId,audios);return{bookId,createdAt:Date.now(),engine:'local-pre-scan',blocks:docs,audioMap,files:[...files].map(f=>({name:f.name,size:f.size,type:classifyEnhFile(f)}))}}
  window.runAIScan=runAIScan;

  function renderScanDraft(draft){const host=document.getElementById('scanResult'),bookId=draft.bookId;if(!host)return;
    const cats={};draft.blocks.forEach(b=>cats[b.kind]=(cats[b.kind]||0)+1);
    host.innerHTML=`<div class="ai-scan-head"><div><h2>AI Scan Preview ✨</h2><p class="muted">AI sẽ đề xuất, em duyệt trước khi import. Mục chưa chắc được đánh dấu À vérifier.</p></div><span class="pill">${draft.blocks.length} blocks</span><span class="pill">${draft.audioMap.length} audio</span></div>
    <div class="ai-summary">${Object.entries(cats).map(([k,n])=>`<span class="pill">${typeLabel[k]||k} · ${n}</span>`).join('')}</div>
    <h3>1. Nội dung & dạng bài</h3><div class="ai-blocks">${draft.blocks.map((b,i)=>`<div class="ai-block"><div class="ai-badge">${i+1}</div><div class="grow min0"><b>${typeLabel[b.kind]||b.kind}</b><div class="muted">${esc(b.source)} · confidence ${Math.round((b.confidence||0)*100)}%</div>${b.content?`<details><summary>Xem nội dung scan</summary><div class="scan-text">${esc(b.content).slice(0,1800)}</div></details>`:'<div class="muted">PDF/Word/scan cần backend OCR + AI để đọc nội dung thật.</div>'}</div><select data-ai-kind="${i}">${['theory','mcq','truefalse','fill','open','listening','corrige','transcript'].map(k=>`<option value="${k}" ${k===b.kind?'selected':''}>${typeLabel[k]}</option>`).join('')}</select>${targetSelect(bookId,b.target||'book',`data-ai-target="${i}"`)}</div>`).join('')}</div>
    <h3>2. Audio matching</h3>${draft.audioMap.length?`<div class="ai-audio-list">${draft.audioMap.map((a,i)=>`<div class="ai-block"><div class="material-file-icon">🎧</div><div class="grow min0"><b>${esc(a.name)}</b><div class="muted">${a.track!=null?'Piste '+a.track+' · ':''}${Math.round(a.confidence*100)}% · ${esc(a.reason)}</div></div>${targetSelect(bookId,a.target,`data-audio-target="${i}"`)}<span class="${a.confidence<.6?'verify':'ok-map'}">${a.confidence<.6?'À vérifier':'Proposé'}</span></div>`).join('')}</div>`:'<div class="notice muted">Không có audio trong lần import này.</div>'}
    <div class="ai-actions"><button id="saveAIScan">✓ Import cấu trúc đã duyệt</button><button class="ghost" id="cancelAIScan">Huỷ</button></div>`;
    document.getElementById('cancelAIScan').onclick=()=>host.innerHTML='';
    document.getElementById('saveAIScan').onclick=()=>{document.querySelectorAll('[data-ai-kind]').forEach(x=>draft.blocks[+x.dataset.aiKind].kind=x.value);document.querySelectorAll('[data-ai-target]').forEach(x=>draft.blocks[+x.dataset.aiTarget].target=x.value);document.querySelectorAll('[data-audio-target]').forEach(x=>draft.audioMap[+x.dataset.audioTarget].target=x.value);AI.courses[bookId]=AI.courses[bookId]||{imports:[]};AI.courses[bookId].imports.push(draft);saveAI();
      S.imports=S.imports||[];let mappedAudio=draft.audioMap.map(a=>({name:a.name,type:'Audio',size:a.size,target:a.target,aiConfidence:a.confidence}));if(mappedAudio.length)S.imports.push({id:'ai-'+Date.now(),name:'AI audio mapping',bookId,target:'book',scopeLabel:'AI mapped audio',files:mappedAudio});save();location='book.html?id='+encodeURIComponent(bookId)};
  }
  window.renderScanDraft=renderScanDraft;

  window.renderAILessonContent=function(bookId,u,l){let course=AI.courses[bookId],imports=course?.imports||[],blocks=[];imports.forEach(im=>im.blocks.forEach(b=>{if(b.target===`${u}:${l}`)blocks.push(b)}));if(!blocks.length)return'';
    return `<section class="lesson-source-block"><div class="lesson-section-title"><span>02</span><h3>Nội dung AI đã cấu trúc</h3></div>${blocks.map((b,i)=>`<div class="structured-block"><div class="structured-head"><span class="pill">${typeLabel[b.kind]||b.kind}</span><b>${esc(b.title||('Block '+(i+1)))}</b></div>${b.content?`<div class="scan-text">${esc(b.content)}</div>`:'<p class="muted">Block đã được phân loại nhưng chưa có text extract.</p>'}${b.kind==='mcq'?'<div class="mcq-demo"><label><input type="radio" disabled> A</label><label><input type="radio" disabled> B</label><label><input type="radio" disabled> C</label><label><input type="radio" disabled> D</label></div>':''}</div>`).join('')}</section>`}

  const style=document.createElement('style');style.textContent=`.ai-scan-head,.ai-actions,.structured-head{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.ai-scan-head>div:first-child{flex:1}.ai-summary{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0 18px}.ai-blocks,.ai-audio-list{display:grid;gap:9px}.ai-block{display:grid;grid-template-columns:38px minmax(0,1fr) minmax(140px,200px) minmax(190px,300px);gap:9px;align-items:center;border:1px solid var(--line);border-radius:14px;padding:10px;background:#fff}.ai-badge{width:34px;height:34px;border-radius:10px;background:#fff0f5;display:grid;place-items:center;font-weight:900}.scan-text{white-space:pre-wrap;background:#fffafb;border:1px solid var(--line);border-radius:10px;padding:10px;margin-top:8px;max-height:260px;overflow:auto}.verify{font-size:12px;background:#fff1d9;padding:6px 8px;border-radius:999px}.ok-map{font-size:12px;background:#edf8f0;padding:6px 8px;border-radius:999px}.ai-actions{margin-top:16px}.structured-block{border:1px solid var(--line);border-radius:14px;padding:13px;margin:10px 0;background:#fff}.mcq-demo{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.mcq-demo label{border:1px solid var(--line);padding:8px;border-radius:10px}@media(max-width:900px){.ai-block{grid-template-columns:38px minmax(0,1fr)}.ai-block>select,.ai-block>.verify,.ai-block>.ok-map{grid-column:2/-1}.mcq-demo{grid-template-columns:1fr 1fr}}`;document.head.appendChild(style);
})();