// Lingo Bloom backend client. Browser-safe Supabase URL + publishable key only.
(function(){
  const CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm';
  const cfg=window.LINGO_BACKEND||{};
  let client=null,modulePromise=null;
  const listeners=new Set();
  const state={enabled:!!(cfg.enabled&&cfg.supabaseUrl&&cfg.publishableKey),session:null,user:null,error:null};
  function emit(){listeners.forEach(fn=>{try{fn({...state})}catch{}})}
  async function init(){if(!state.enabled)return state;if(client)return state;try{modulePromise=modulePromise||import(CDN);const {createClient}=await modulePromise;client=createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await client.auth.getSession();if(error)throw error;state.session=data.session||null;state.user=data.session?.user||null;client.auth.onAuthStateChange((_event,session)=>{state.session=session||null;state.user=session?.user||null;emit()});emit();return state}catch(e){state.error=e;emit();throw e}}
  async function need(){await init();if(!client)throw new Error('Backend chưa được cấu hình.');return client}
  function requireUser(){if(!state.user)throw new Error('Bạn chưa đăng nhập.');return state.user}
  async function signInGoogle(){const c=await need();const base=location.href.replace(/[^/]+(?:\?.*)?$/,'');const redirectTo=base+'index.html';const {data,error}=await c.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)throw error;return data}
  async function signUp(email,password){const c=await need();const {data,error}=await c.auth.signUp({email,password});if(error)throw error;return data}
  async function signIn(email,password){const c=await need();const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;return data}
  async function signOut(){const c=await need();const {error}=await c.auth.signOut();if(error)throw error}
  async function saveUserState(localState){const c=await need();const u=requireUser();const {data,error}=await c.from('user_state').upsert({user_id:u.id,state:localState,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select().single();if(error)throw error;return data}
  async function loadUserState(){const c=await need();const u=requireUser();const {data,error}=await c.from('user_state').select('state,updated_at').eq('user_id',u.id).maybeSingle();if(error)throw error;return data}
  async function ensureCourse(bookId,title,language='fr'){const c=await need();const u=requireUser();const {data:existing,error:e1}=await c.from('courses').select('id,owner_id').eq('id',bookId).maybeSingle();if(e1)throw e1;if(existing)return existing;const {data,error}=await c.from('courses').insert({id:bookId,owner_id:u.id,title,language,source_kind:'user-library'}).select().single();if(error)throw error;await c.from('user_courses').upsert({user_id:u.id,course_id:bookId,granted_by:u.id},{onConflict:'user_id,course_id'});return data}
  async function listMyCourses(){const c=await need();const u=requireUser();const {data,error}=await c.from('user_courses').select('course_id,granted_by,access_code,created_at').eq('user_id',u.id);if(error)throw error;const {data:owned,error:e2}=await c.from('courses').select('id').eq('owner_id',u.id);if(e2)throw e2;return{granted:(data||[]).map(x=>x.course_id),owned:(owned||[]).map(x=>x.id)}}
  async function redeemCourseCode(code){const c=await need();requireUser();const {data,error}=await c.rpc('redeem_course_code',{p_code:code});if(error)throw error;return data}
  async function createCourseCode({bookId,code,maxUses=null,expiresAt=null}){const c=await need();requireUser();const {data,error}=await c.rpc('create_course_code',{p_course_id:bookId,p_code:code,p_max_uses:maxUses,p_expires_at:expiresAt});if(error)throw error;return data}
  async function listCourseCodes(bookId){const c=await need();requireUser();const {data,error}=await c.from('course_access_codes').select('code,max_uses,uses,expires_at,revoked,created_at').eq('course_id',bookId).order('created_at',{ascending:false});if(error)throw error;return data||[]}
  async function revokeCourseCode(code){const c=await need();requireUser();const {error}=await c.from('course_access_codes').update({revoked:true}).eq('code',code);if(error)throw error}
  async function uploadMaterial({bookId,file,unitIndex=null,lessonIndex=null,fileType='Other'}){const c=await need();const u=requireUser();const clean=(file.name||'file').replace(/[^a-zA-Z0-9._-]+/g,'_');const path=`${u.id}/${bookId}/${crypto.randomUUID()}-${clean}`;const {data:up,error:upErr}=await c.storage.from('materials').upload(path,file,{upsert:false,contentType:file.type||undefined});if(upErr)throw upErr;const {data,error}=await c.from('materials').insert({owner_id:u.id,course_id:bookId,unit_index:unitIndex,lesson_index:lessonIndex,file_name:file.name,file_type:fileType,storage_path:up.path}).select().single();if(error){await c.storage.from('materials').remove([up.path]);throw error}return data}
  async function deleteMaterial(material){const c=await need();requireUser();if(material.storage_path){const {error:se}=await c.storage.from('materials').remove([material.storage_path]);if(se)throw se}const {error}=await c.from('materials').delete().eq('id',material.id);if(error)throw error}
  async function listMaterials(bookId){const c=await need();requireUser();const {data,error}=await c.from('materials').select('*').eq('course_id',bookId).order('created_at');if(error)throw error;return data||[]}
  async function getMaterialUrl(materialId){const c=await need();requireUser();const {data,error}=await c.functions.invoke('material-url',{body:{material_id:materialId}});if(error)throw error;return data}
  async function loadLessonContent(bookId,u,l){const c=await need();requireUser();const {data,error}=await c.from('lesson_content').select('*').eq('course_id',bookId).eq('unit_index',u).eq('lesson_index',l).order('block_order');if(error)throw error;return data||[]}

  // Social
  async function getMyProfile(){const c=await need();const u=requireUser();const {data,error}=await c.from('profiles').select('*').eq('user_id',u.id).single();if(error)throw error;return data}
  async function updateMyProfile(patch){const c=await need();const u=requireUser();const allowed=['display_name','username','avatar_url','bio','library_visibility','achievements_visibility','streak_visibility','scores_visibility'];const clean={};allowed.forEach(k=>{if(k in patch)clean[k]=patch[k]});clean.updated_at=new Date().toISOString();const {data,error}=await c.from('profiles').update(clean).eq('user_id',u.id).select().single();if(error)throw error;return data}
  async function searchUsers(query){const c=await need();const u=requireUser();const q=(query||'').trim();if(q.length<2)return[];const safe=q.replace(/[,%()]/g,' ');const {data,error}=await c.from('profiles').select('user_id,display_name,username,avatar_url,bio').neq('user_id',u.id).or(`display_name.ilike.%${safe}%,username.ilike.%${safe}%`).limit(20);if(error)throw error;return data||[]}
  async function listFriendships(){const c=await need();const u=requireUser();const {data,error}=await c.from('friendships').select('*').or(`user_id.eq.${u.id},friend_id.eq.${u.id}`).order('created_at',{ascending:false});if(error)throw error;const ids=[...new Set((data||[]).flatMap(r=>[r.user_id,r.friend_id]).filter(id=>id!==u.id))];let profiles=[];if(ids.length){const r=await c.from('profiles').select('user_id,display_name,username,avatar_url,bio').in('user_id',ids);if(r.error)throw r.error;profiles=r.data||[]}const pm=Object.fromEntries(profiles.map(p=>[p.user_id,p]));return(data||[]).map(r=>({...r,other:r.user_id===u.id?pm[r.friend_id]:pm[r.user_id],direction:r.user_id===u.id?'outgoing':'incoming'}))}
  async function sendFriendRequest(friendId){const c=await need();const u=requireUser();const {data,error}=await c.from('friendships').insert({user_id:u.id,friend_id:friendId,status:'pending'}).select().single();if(error)throw error;return data}
  async function acceptFriendRequest(requesterId){const c=await need();const u=requireUser();const {data,error}=await c.from('friendships').update({status:'accepted'}).eq('user_id',requesterId).eq('friend_id',u.id).eq('status','pending').select().single();if(error)throw error;return data}
  async function removeFriendship(otherId){const c=await need();const u=requireUser();const {error}=await c.from('friendships').delete().or(`and(user_id.eq.${u.id},friend_id.eq.${otherId}),and(user_id.eq.${otherId},friend_id.eq.${u.id})`);if(error)throw error}
  async function getSocialProfile(userId){const c=await need();requireUser();const {data,error}=await c.rpc('get_social_profile',{p_user_id:userId});if(error)throw error;return data}

  async function invokeAIScan(payload){const c=await need();requireUser();const {data,error}=await c.functions.invoke('ai-scan',{body:payload});if(error)throw error;return data}
  function onChange(fn){listeners.add(fn);fn({...state});return()=>listeners.delete(fn)}
  window.LingoBackend={init,signInGoogle,signUp,signIn,signOut,saveUserState,loadUserState,ensureCourse,listMyCourses,redeemCourseCode,createCourseCode,listCourseCodes,revokeCourseCode,uploadMaterial,deleteMaterial,listMaterials,getMaterialUrl,loadLessonContent,getMyProfile,updateMyProfile,searchUsers,listFriendships,sendFriendRequest,acceptFriendRequest,removeFriendship,getSocialProfile,invokeAIScan,onChange,get client(){return client},get state(){return state}};
  if(state.enabled)init().catch(console.error);
})();
