const ENH_KEY='lingo-bloom-enhancements-v1';
const ENH=JSON.parse(localStorage.getItem(ENH_KEY)||'null')||{theme:{accent:'#ef9fbd',soft:'#ffe3ed',compact:false},profile:{displayName:'Thy',username:'serulian298',bio:'Learning languages one tiny step at a time 🌷',avatar:'🐰'}};
const saveEnh=()=>localStorage.setItem(ENH_KEY,JSON.stringify(ENH));
function applyEnhTheme(){document.documentElement.style.setProperty('--pink',ENH.theme.accent||'#ef9fbd');document.documentElement.style.setProperty('--pink2',ENH.theme.soft||'#ffe3ed');document.body.classList.toggle('compact',!!ENH.theme.compact)}
function matForBook(id){S.imports=S.imports||[];return S.imports.filter(x=>x.bookId===id)}
function canSeeBook(id){return typeof canAccessBook!=='function'||canAccessBook(id)}
function visibleBooks(){return Object.entries(BOOKS).filter(([id])=>canSeeBook(id))}
function profileUrl(){return `${location.origin}${location.pathname.replace(/[^/]+$/,'')}profile.html?u=${encodeURIComponent(ENH.profile.username||'user')}`}

library=function(){books.innerHTML=visibleBooks().map(([id,b])=>{let total=b.units.reduce((n,u)=>n+u[1].length,0),done=b.units.reduce((n,u,ui)=>n+u[1].filter((_,li)=>S.done[key(id,ui,li)]).length,0),p=Math.round(done/Math.max(total,1)*100),m=matForBook(id).length;return `<div class="book" onclick="location='book.html?id=${id}'"><div class="book-title-row"><h2>${b.emoji} ${b.title}</h2><span class="pill">📎 ${m}</span></div><p>${b.subtitle}</p><span class="pill">${b.units.length} units</span><span class="pill">${p}% complete</span><div class="progress"><div class="bar" style="width:${p}%"></div></div></div>`}).join('')||'<div class="notice">Chưa có giáo trình. Nhập mã sách để bắt đầu.</div>'}

function renderCourseMaterials(id){let el=document.getElementById('bookMaterials');if(!el)return;let a=matForBook(id);el.innerHTML=`<div class="section-head"><div><h2>📎 Materials</h2><p class="muted">Audio, PDF, transcript, corrigé… gắn riêng với giáo trình này.</p></div><a class="btn" href="import.html?book=${encodeURIComponent(id)}">＋ Add materials</a></div>`+(a.length?a.map((x,i)=>`<div class="material"><div class="grow"><b>${i+1}. ${x.name}</b><div class="muted">${x.scopeLabel||'Toàn bộ sách'} · ${x.files.length} file</div></div><div class="chips">${x.files.slice(0,4).map(f=>`<span class="pill">${f.type||'File'} · ${f.name}</span>`).join('')}${x.files.length>4?`<span class="pill">+${x.files.length-4}</span>`:''}</div></div>`).join(''):'<div class="notice">Chưa có tài liệu bổ sung cho giáo trình này.</div>')}

book=function(){let q=new URLSearchParams(location.search),id=q.get('id')||'reussite';if(!canSeeBook(id)){location='access.html?need='+encodeURIComponent(id);return}let b=BOOKS[id];if(!b)return;bookTitle.textContent=b.title;let total=0,done=0;bookTree.innerHTML=b.units.map((u,ui)=>`<section class="unit"><h2>Unit ${ui+1}. ${u[0]}</h2>${u[1].map((l,li)=>{let K=key(id,ui,li),sc=S.scores[K],st=S.done[K]?'✓':sc!=null&&sc<70?'◐':'○';total++;if(S.done[K])done++;return `<div class="lesson"><div class="lesson-no">${ui+1}.${li+1}</div><div class="grow"><b>${st} ${l}</b><div class="muted">${u[2].map(s=>names[s]||s).join(' · ')}</div></div>${sc!=null?`<span class="status">${sc}%</span>`:''}<a class="btn ghost" href="lesson.html?b=${id}&u=${ui}&l=${li}">Ouvrir</a></div>`}).join('')}</section>`).join('');let p=Math.round(done/Math.max(total,1)*100);bookPct.textContent=p+'%';bookBar.style.width=p+'%';renderCourseMaterials(id);let a=document.getElementById('bookAccessPanel');if(a&&typeof bookAccessPanel==='function')a.innerHTML=bookAccessPanel(id)}

lesson=function(){let q=new URLSearchParams(location.search),b=q.get('b')||'reussite',u=+q.get('u')||0,l=+q.get('l')||0;if(!canSeeBook(b)){location='access.html?need='+encodeURIComponent(b);return}let K=key(b,u,l),U=BOOKS[b].units[u],title=U[1][l],num=`${u+1}.${l+1}`;S.last=K;save();lessonTitle.textContent=`Bài ${num} · ${title}`;lessonSub.textContent=BOOKS[b].title+' · Unit '+(u+1)+' · '+U[0];let mats=matForBook(b).filter(x=>x.target==='book'||x.target===`${u}:${l}`||x.target===`unit:${u}`||!x.target);lessonBox.innerHTML=`${U[2].includes('CO')?'<div class="notice"><b>🎧 Audio</b><p class="muted">Audio thêm từ Materials của chính giáo trình này sẽ được map vào đúng bài.</p></div>':''}<h3>Exercise ${num}.1</h3><p>Prototype chấm điểm/progress. Nội dung nguồn sẽ được import vào đúng bài sau.</p><div class="button-row"><button onclick="finish('${K}',100)">100%</button><button class="alt" onclick="finish('${K}',80)">80%</button><button class="ghost" onclick="finish('${K}',60)">60%</button><button class="ghost" onclick="finish('${K}',40)">40%</button></div><div id="answerBox" style="margin-top:14px"></div>${mats.length?`<div class="notice" style="margin-top:14px"><b>📎 Tài liệu liên kết</b>${mats.map(x=>`<p>${x.name} · ${x.files.map(f=>f.name).join(', ')}</p>`).join('')}</div>`:''}<div class="notice" style="margin-top:14px"><b>✅ Corrigé · 💬 Transcript</b><p>Hai phần này sẽ hiện ngay trong lesson sau khi làm bài.</p></div>`;stats(K)}

function classifyEnhFile(f){let x=f.name.toLowerCase();if(/\.(mp3|m4a|wav|ogg)$/.test(x))return'Audio';if(/corrig|answer|reponse|réponse/.test(x))return'Corrigé';if(/transcript|transcription/.test(x))return'Transcript';if(/exercise|exercice|cahier|workbook/.test(x))return'Exercises';if(/reading|lecture|article/.test(x))return'Reading';if(/\.(pdf|doc|docx|txt)$/.test(x))return'Theory';if(/\.(jpg|jpeg|png)$/.test(x))return'Scan';return'Other'}
importer=function(){let bookSel=document.getElementById('bookTarget'),unitSel=document.getElementById('unitTarget'),lessonSel=document.getElementById('lessonTarget'),q=new URLSearchParams(location.search),preset=q.get('book');if(!bookSel)return;bookSel.innerHTML=visibleBooks().map(([id,b])=>`<option value="${id}" ${id===preset?'selected':''}>${b.emoji} ${b.title}</option>`).join('');function fillUnits(){let b=BOOKS[bookSel.value];unitSel.innerHTML='<option value="">Toàn bộ sách</option>'+b.units.map((u,i)=>`<option value="${i}">Unit ${i+1}. ${u[0]}</option>`).join('');fillLessons()}function fillLessons(){let b=BOOKS[bookSel.value],u=unitSel.value;if(u===''){lessonSel.innerHTML='<option value="">Không chọn lesson</option>';lessonSel.disabled=true;return}lessonSel.disabled=false;lessonSel.innerHTML='<option value="">Cả Unit</option>'+b.units[+u][1].map((l,i)=>`<option value="${i}">${+u+1}.${i+1} ${l}</option>`).join('')}bookSel.onchange=fillUnits;unitSel.onchange=fillLessons;fillUnits();scanBtn.onclick=()=>{let fs=[...files.files],bookId=bookSel.value,n=importName.value||('Materials · '+BOOKS[bookId].title);if(!fs.length)return alert('Chọn file trước');let cats={},mapped=fs.map(f=>{let type=classifyEnhFile(f);cats[type]=(cats[type]||0)+1;return{name:f.name,type}}),u=unitSel.value,l=lessonSel.value,target='book',scopeLabel='Toàn bộ sách';if(u!==''&&l!==''){target=`${u}:${l}`;scopeLabel=`Bài ${+u+1}.${+l+1} · ${BOOKS[bookId].units[+u][1][+l]}`}else if(u!==''){target=`unit:${u}`;scopeLabel=`Unit ${+u+1} · ${BOOKS[bookId].units[+u][0]}`}scanResult.innerHTML=`<div class="notice"><h3>Import → ${BOOKS[bookId].title}</h3><p><b>Gắn vào:</b> ${scopeLabel}</p>${Object.entries(cats).map(x=>`<p><b>${x[0]}</b> · ${x[1]}</p>`).join('')}<button id="confirmImp">Lưu vào giáo trình này</button></div>`;confirmImp.onclick=()=>{S.imports.push({id:'mat-'+Date.now(),name:n,bookId,target,scopeLabel,files:mapped});save();alert('Đã gắn tài liệu vào '+BOOKS[bookId].title+' 🌸');location='book.html?id='+bookId}}}

function settingsPage(){applyEnhTheme();accent.value=ENH.theme.accent;compact.checked=!!ENH.theme.compact;displayName.value=ENH.profile.displayName;username.value=ENH.profile.username;bio.value=ENH.profile.bio;avatar.value=ENH.profile.avatar;saveSettings.onclick=()=>{ENH.theme.accent=accent.value;ENH.theme.soft='#ffe3ed';ENH.theme.compact=compact.checked;ENH.profile={displayName:displayName.value||'Learner',username:(username.value||'learner').replace(/\s+/g,'-'),bio:bio.value,avatar:avatar.value||'🌸'};saveEnh();applyEnhTheme();alert('Đã lưu cá nhân hóa 🌸')}}
function profilePage(){let p=ENH.profile,shared=new URLSearchParams(location.search).get('u');profileCard.innerHTML=`<div class="profile-head"><div class="avatar">${p.avatar||'🌸'}</div><div><h2>${p.displayName}</h2><p class="muted">@${p.username}</p><p>${p.bio||''}</p></div></div><div class="kpis"><div class="kpi">Lessons<b>${Object.values(S.done||{}).filter(Boolean).length}</b></div><div class="kpi">Books<b>${typeof visibleBooks==='function'?visibleBooks().length:Object.keys(BOOKS).length}</b></div><div class="kpi">Mastery<b>${typeof overall==='function'?overall():0}%</b></div><div class="kpi">Streak<b>${window.SOCIAL?.profile?.streak||0}</b></div></div>`;shareProfile.onclick=async()=>{let url=profileUrl(),text=`Kết bạn với mình trên Lingo Bloom 🌸 ${url}`;if(navigator.share)await navigator.share({title:'Lingo Bloom profile',text,url});else{await navigator.clipboard.writeText(url);alert('Đã copy link profile')}};friendAction.textContent=shared&&shared!==p.username?'＋ Kết bạn':'Link chia sẻ của bạn';friendAction.onclick=()=>{if(shared&&shared!==p.username)alert('Lời mời kết bạn sẽ được gửi thật sau khi nối Supabase.');else shareProfile.click()}}
window.addEventListener('DOMContentLoaded',()=>{applyEnhTheme();if(document.body.dataset.page==='settings')settingsPage();if(document.body.dataset.page==='profile')profilePage()});
