const SOCIAL_KEY='petit-french-social-v1';
let SOCIAL=JSON.parse(localStorage.getItem(SOCIAL_KEY)||'null')||{
 profile:{displayName:'Thy',bio:'J’apprends le français 🌷',visibility:{streak:'friends',achievements:'friends',library:'friends',scores:'private'},streak:0},
 friends:[{id:'demo-linh',name:'Linh',streak:7,books:['reussite'],last:'Production écrite · Analyser la consigne'},{id:'demo-minh',name:'Minh',streak:3,books:['c3'],last:'Semaine 4 · Compréhension orale'}],
 groups:[{id:'g1',name:'B2 Croissant Club 🥐',bookId:'reussite',members:['Thy','Linh'],thread:[]}]
};
const saveSocial=()=>localStorage.setItem(SOCIAL_KEY,JSON.stringify(SOCIAL));
function socialPage(){renderProfile();renderFriends();renderGroups();renderSuggestions()}
function renderProfile(){let p=SOCIAL.profile;profileBox.innerHTML=`<div class="profile-head"><div class="avatar">🐰</div><div><h2>${p.displayName}</h2><p>${p.bio}</p><span class="pill">🔥 ${p.streak} day streak</span><span class="pill">📚 ${Object.keys(S.done||{}).filter(k=>S.done[k]).length} lessons completed</span></div></div><h3>Privacy</h3>${['streak','achievements','library','scores'].map(k=>`<label class="setting"><span>${k}</span><select onchange="SOCIAL.profile.visibility['${k}']=this.value;saveSocial()"><option value="public" ${p.visibility[k]==='public'?'selected':''}>Public</option><option value="friends" ${p.visibility[k]==='friends'?'selected':''}>Friends</option><option value="private" ${p.visibility[k]==='private'?'selected':''}>Only me</option></select></label>`).join('')}`}
function renderFriends(){friendsBox.innerHTML=SOCIAL.friends.map(f=>`<div class="lesson"><div class="avatar sm">🌸</div><div class="grow"><b>${f.name}</b><div class="muted">🔥 ${f.streak} · ${f.last}</div></div><button class="ghost" onclick="studyWith('${f.id}')">Học cùng</button></div>`).join('')}
function renderSuggestions(){let owned=[...new Set([...(window.ACCESS?.owned||[]),...(window.ACCESS?.granted||[])])];let matches=SOCIAL.friends.filter(f=>f.books.some(b=>owned.includes(b)));suggestBox.innerHTML=matches.length?matches.map(f=>{let common=f.books.find(b=>owned.includes(b));return `<div class="notice"><b>✨ ${f.name} cũng đang học ${BOOKS[common]?.title||common}</b><p class="muted">Gợi ý tạo Study Group hoặc gửi bài đang học cho nhau.</p><button onclick="createGroupWith('${f.id}','${common}')">Tạo nhóm học</button></div>`}).join(''):'<div class="notice">Khi bạn bè có cùng một quyển sách, gợi ý học cùng sẽ hiện ở đây.</div>'}
function renderGroups(){groupsBox.innerHTML=SOCIAL.groups.map(g=>`<div class="book"><h2>👥 ${g.name}</h2><p>${g.bookId?BOOKS[g.bookId]?.title:'General'} · ${g.members.length} members</p><button onclick="openGroup('${g.id}')">Mở nhóm</button></div>`).join('')}
function studyWith(id){let f=SOCIAL.friends.find(x=>x.id===id);if(!f)return;let owned=[...new Set([...(ACCESS?.owned||[]),...(ACCESS?.granted||[])])],common=f.books.find(b=>owned.includes(b));if(common)createGroupWith(id,common);else alert('Hai người chưa có sách chung. Gửi mã sách trước nhé 🔑')}
function createGroupWith(id,bookId){let f=SOCIAL.friends.find(x=>x.id===id);if(!f)return;let existing=SOCIAL.groups.find(g=>g.bookId===bookId&&g.members.includes(f.name));if(!existing){SOCIAL.groups.push({id:'g'+Date.now(),name:`${BOOKS[bookId]?.title||'Study'} · ${f.name}`,bookId,members:[SOCIAL.profile.displayName,f.name],thread:[]});saveSocial()}renderGroups();alert('Đã tạo nhóm học 🌸')}
function openGroup(id){location='group.html?id='+encodeURIComponent(id)}
function groupPage(){let id=new URLSearchParams(location.search).get('id'),g=SOCIAL.groups.find(x=>x.id===id)||SOCIAL.groups[0];if(!g){groupTitle.textContent='Study Group';return}groupTitle.textContent=g.name;groupMeta.textContent=`${g.members.join(' · ')}${g.bookId?' · '+(BOOKS[g.bookId]?.title||g.bookId):''}`;thread.innerHTML=g.thread.length?g.thread.map(m=>`<div class="notice"><b>${m.by}</b><p>${m.text}</p>${m.link?`<a class="btn ghost" href="${m.link}">Mở bài được chia sẻ</a>`:''}</div>`).join(''):'<div class="notice">Chưa có tin nhắn. Hãy gửi một bài trong sách để cùng thảo luận.</div>';sendMessage.onclick=()=>{let text=groupMessage.value.trim();if(!text)return;g.thread.push({by:SOCIAL.profile.displayName,text});saveSocial();groupPage()}}
function shareCurrentLessonToGroup(bookId,u,l){let choices=SOCIAL.groups.filter(g=>g.bookId===bookId);if(!choices.length){alert('Chưa có Study Group cho quyển này. Tạo nhóm ở Friends trước nhé.');return}let g=choices[0],title=BOOKS[bookId].units[u][1][l],link=`lesson.html?b=${encodeURIComponent(bookId)}&u=${u}&l=${l}`;g.thread.push({by:SOCIAL.profile.displayName,text:`Cùng xem bài này: ${title}`,link});saveSocial();alert('Đã gửi bài vào '+g.name+' 🌸')}
window.addEventListener('DOMContentLoaded',()=>{if(document.body.dataset.page==='social')socialPage();if(document.body.dataset.page==='group')groupPage()});